### ISSUE TITLE
Generation in Vulkan-Docs CI failed due to change on ash side

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#936] opened 2024-08-21 13:38 UTC
https://github.com/KhronosGroup/Vulkan-Docs/actions/runs/10419060444/job/29056703428 is failing. This seems to be something that changed on the ash side because the same job succeeded 5 days ago, but is failing now when I re-ran it.

**Comment by MarijnS95** [comment] 2024-08-21 19:52
That was caused by https://github.com/ash-rs/ash/commit/a00c45eb894c5c141a0c7366508dd4bd4eec0b4b which I merged yesterday. We've never ran with this on newer `vk.xml` than `1.3.281`, where `videocodecs` was introduced.

I've just merged https://github.com/ash-rs/ash/pull/927 which adds support for this element, [re-ran the CI](https://github.com/KhronosGroup/Vulkan-Docs/actions/runs/10419060444) and it's green again. Thanks for letting me know!

**Closed by MarijnS95** 2024-08-21 19:52 UTC
