### ISSUE TITLE
Examples Issues on Linux

### ISSUE THREAD

**Issue by matt328** [ash-rs/ash#842] opened 2023-12-02 18:03 UTC
*edit actually it isn't specific to wayland, same error occurs on x11 as well.

I've installed the Vulkan SDK and configured the environment variables as per the linked SO post, but still get the following error from both triangle and texture examples when running on Linux using Wayland.

`Failed to find vkGetDeviceProcAddr in layer "libVkLayer_MESA_device_select.so"`

This happens on both the master branch and the 0.37.3 tag of ash-rs with vulkan sdk version 1.3.250.1.

If there's any other diagnostic logs that would be helpful I can provide those too.

**Comment by Ralith** [comment] 2023-12-02 18:38
That looks like an issue in your environment, perhaps a harmless diagnostic due to using a much newer SDK than your system was built for. Do the examples actually fail to run?

Generally on Linux you should install the SDK components you're interested in from your distro's package manager. You likely don't *need* anything but the runtime components most systems have by default, though the validation layers are worth having.

**Comment by MarijnS95** [comment] 2023-12-02 19:00
This indeed looks like a broken environment. The `json` file for this layer is supposed to tell what functions to load from the library, and it seems you ended up with a desynced environment. For example, it is possible that the function configured in `VkLayer_MESA_device_select.json` (from the latest SDK) mismatches with the actual `libVkLayer_MESA_device_select.so` installed on your system and available in `PATH`.

When setting up a Vulkan environment by hand you're pretty much on your own, and all errors you'll run into are general Vulkan issues that have no (in)direct relation to `ash`.

That said we should clean up the ancient `README` to no longer reference a 7-year old SO post about Nvidia drivers.

**Comment by matt328** [comment] 2023-12-03 16:00
https://gist.github.com/matt328/7f16c38208d62a7dca43f4d925bf21d5 The log was long so I put it in a separate gist.  This is not directly from the ash examples, but from my own project (https://github.com/matt328/triton-sr2) that follows the ash examples right up until the swapchain creation dies and logs the same warnings and segfaults in exactly the same place.

**Comment by matt328** [comment] 2023-12-03 21:34
![image](https://github.com/ash-rs/ash/assets/706207/35f78247-1855-471e-b39a-d7ddf0f6386b)

I think this shows that it is not null right?  It's really strange because I have a C++ application using vulkan that I wrote that works fine.

**Comment by codecnotsupported** [comment] 2023-12-03 21:55
I've a hunch that some misconfiguration is causing the validation layers to crash.

Could you comment out.
https://github.com/ash-rs/ash/blob/befb8cdd36aa30e9c1976f64ef2b727c982fd636/ash-examples/src/lib.rs#L225-L231
and
https://github.com/ash-rs/ash/blob/befb8cdd36aa30e9c1976f64ef2b727c982fd636/ash-examples/src/lib.rs#L261

And recompile & run the triangle example again?

**Comment by matt328** [comment] 2023-12-03 23:42
I hadn't thought to try eliminating validation layers, but sadly that still results in the same ol segfault on creating the swapchain.

```
➜ cargo run -p ash-examples --bin triangle
   Compiling ash-examples v0.1.0 (/home/matt/Projects/ash/ash-examples)
warning: unused variable: `layers_names_raw`
   --> ash-examples/src/lib.rs:228:17
    |
228 |             let layers_names_raw: Vec<*const c_char> = layer_names
    |                 ^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_layers_names_raw`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `ash-examples` (lib) generated 1 warning (run `cargo fix --lib -p ash-examples` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 2.09s
     Running `target/debug/triangle`
INFO:
GENERAL [Loader Message (0)] : linux_read_sorted_physical_devices:

INFO:
GENERAL [Loader Message (0)] :      Original order:

INFO:
GENERAL [Loader Message (0)] :            [0] llvmpipe (LLVM 15.0.7, 256 bits)

INFO:
GENERAL [Loader Message (0)] :            [1] NVIDIA RTX 2000 Ada Generation Laptop GPU

INFO:
GENERAL [Loader Message (0)] :      Sorted order:

INFO:
GENERAL [Loader Message (0)] :            [0] NVIDIA RTX 2000 Ada Generation Laptop GPU  

INFO:
GENERAL [Loader Message (0)] :            [1] llvmpipe (LLVM 15.0.7, 256 bits)  

INFO:
GENERAL [Loader Message (0)] : linux_read_sorted_physical_devices:

INFO:
GENERAL [Loader Message (0)] :      Original order:

INFO:
GENERAL [Loader Message (0)] :            [0] llvmpipe (LLVM 15.0.7, 256 bits)

INFO:
GENERAL [Loader Message (0)] :            [1] NVIDIA RTX 2000 Ada Generation Laptop GPU

INFO:
GENERAL [Loader Message (0)] :      Sorted order:

INFO:
GENERAL [Loader Message (0)] :            [0] NVIDIA RTX 2000 Ada Generation Laptop GPU  

INFO:
GENERAL [Loader Message (0)] :            [1] llvmpipe (LLVM 15.0.7, 256 bits)  

INFO:
GENERAL [Loader Message (0)] : linux_read_sorted_physical_devices:

INFO:
GENERAL [Loader Message (0)] :      Original order:

INFO:
GENERAL [Loader Message (0)] :            [0] llvmpipe (LLVM 15.0.7, 256 bits)

INFO:
GENERAL [Loader Message (0)] :            [1] NVIDIA RTX 2000 Ada Generation Laptop GPU

INFO:
GENERAL [Loader Message (0)] :      Sorted order:

INFO:
GENERAL [Loader Message (0)] :            [0] NVIDIA RTX 2000 Ada Generation Laptop GPU  

INFO:
GENERAL [Loader Message (0)] :            [1] llvmpipe (LLVM 15.0.7, 256 bits)  

INFO:
GENERAL [Loader Message (0)] : linux_read_sorted_physical_devices:

INFO:
GENERAL [Loader Message (0)] :      Original order:

INFO:
GENERAL [Loader Message (0)] :            [0] llvmpipe (LLVM 15.0.7, 256 bits)

INFO:
GENERAL [Loader Message (0)] :            [1] NVIDIA RTX 2000 Ada Generation Laptop GPU

INFO:
GENERAL [Loader Message (0)] :      Sorted order:

INFO:
GENERAL [Loader Message (0)] :            [0] NVIDIA RTX 2000 Ada Generation Laptop GPU  

INFO:
GENERAL [Loader Message (0)] :            [1] llvmpipe (LLVM 15.0.7, 256 bits)  

INFO:
GENERAL [Loader Message (0)] : Failed to find vkGetDeviceProcAddr in layer "libVkLayer_MESA_device_select.so"

INFO:
GENERAL [Loader Message (0)] :        Using "NVIDIA RTX 2000 Ada Generation Laptop GPU" with driver: "libGLX_nvidia.so.0"

[1]    15538 segmentation fault (core dumped)  cargo run -p ash-examples --bin triangle
```

**Comment by matt328** [comment] 2023-12-04 13:42
`return dev->loader_dispatch.extension_terminator_dispatch.CreateSwapchainKHR(device, pCreateCopy, pAllocator,
                                                                                         pSwapchain);`

It gets to that line in wsi.c, then segfaults.  None of the params are null, and CreateSwapchainKHR is not null either.  I have no idea what else to look at.

I don't believe I have any implicit layers installed, the gist I linked earlier should answer that right?  

Debugging drivers is way deeper than I care to get right now, especially given that other vulkan applications, written by me in c++ as well as vkcube and all that work fine.

**Comment by codecnotsupported** [comment] 2023-12-04 14:52
> ![image](https://private-user-images.githubusercontent.com/706207/287551731-c6f2b756-bab1-4baa-b6ec-c1d25b500b4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDE1MDMsIm5iZiI6MTcwMTcwMTIwMywicGF0aCI6Ii83MDYyMDcvMjg3NTUxNzMxLWM2ZjJiNzU2LWJhYjEtNGJhYS1iNmVjLWMxZDI1YjUwMGI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNDQ2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTI1Mzg3MzBjZTJjYmZmNDc3YzY1ZTc1YjBlZjM3YTA4MDViZjE0MzRhNzYxODc3ZDJiMWM2ZDg1NDI4YmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PS5V_gIBl-_Z8uQyAcayWoFrCUMT0uYvn3mUUuhTia8)


> It gets to that line in wsi.c, then segfaults. None of the params are null, and CreateSwapchainKHR is not null either. I have no idea what else to look at.



I didn't notice this earlier because I mistook it as `VkSwapchainCreateInfoKHR.oldSwapchain`
But I think the vkCreateSwapchainKHR.swapchain pointer is null.

**Comment by matt328** [comment] 2023-12-04 17:03
I feel like this is giving up, but I switched to x11 and everything is working again.

**Comment by codecnotsupported** [comment] 2023-12-04 23:58
> sorry for the confusion my initial post might have caused.

No worries, I thought it was interesting case.
Still curious what the root cause was. 
Anyhow, @Ralith, close the issue & write it off as a broken configuration?

**Closed** 2023-12-05 02:26 UTC
