### ISSUE TITLE
Lifetimes for Structures exceed their Builder's lifetime

### ISSUE THREAD

**Issue by CodeCraftTV** [ash-rs/ash#902] opened 2024-04-01 17:15 UTC
When passing in a reference to an array in a builder for example for the `RenderPassCreateInfoBuilder` like this:
```rust
        let create_info = ash::vk::RenderPassCreateInfo::builder()
            .attachments(&[color_attachment])
            .subpasses(&[sub_pass])
            .dependencies(&[dependency])
            .build();
```

After the create_info is build, The slices can be preemptively freed.

Fix suggestion: Introduce a PhantomData with the lifetime of the Builder in such cases.

**Comment by Friz64** [comment] 2024-04-01 17:55
Please see #866. This will be fixed in the new release, which is due very soon.

**Closed** 2024-04-01 18:08 UTC

**Comment by MarijnS95** [comment] 2024-04-01 18:12
Duplicate of #223, #441, #602, #866.
