### ISSUE TITLE
Work around bad drivers that always return VK_INCOMPLETE

### ISSUE THREAD

**Issue by 06393993** [ash-rs/ash#725] opened 2023-03-28 21:36 UTC
For some drivers, `vkGetPhysicalDeviceSurfaceFormatsKHR` may return `VK_INCOMPLETE` with a not-large-enough `formatCount`, which will cause the subsequent call resulting in `VK_INCOMPLETE` again.

See an example to work around this issue in [another C++ project](https://android.googlesource.com/device/generic/vulkan-cereal/+/d6c921e177aa473d926133bf12555b030daf9c29/stream-servers/vulkan/SwapChainStateVk.cpp#179). We may want to add a limit in `read_into_uninitialized_vector` on how many times we loop and panic if that number is exceeded.

**Comment by MarijnS95** [comment] 2023-03-28 22:31
That workaround manually bumps the size and tries again, rather than limiting the amount of times we loop?

**Comment by 06393993** [comment] 2023-03-28 22:53
Yes, the workaround I paste here use a slightly different approach than what I have explained, but either works for me as long as we don't result in an infinite loop when this situation happens.

We see this happens on Windows(and the workaround I paste here is the code for Android Emulator, so it's actually working around an issue on Windows as well). We have lost the data about the `vkGetPhysicalDeviceSurfaceFormatsKHR` case because it happens a long time ago, but we do see the same behavior on `vkEnumeratePhysicaldevices` on a Windows machine: 
ASUS GA502DU-BR7N6 - NVIDIA GTX 1660 Ti Max-Q  - AMD Ryzen 7 3750H. The driver versions are Nvidia: 31.0.15.2849, and AMD: 26.20.11026.3002. It is probably because of a conflict between the AMD and the Nvidia layers. 

This problem can be very much related to https://stackoverflow.com/q/68109171, but we are using a ToT Vulkan loader, so it also shouldn't be a bug in the Windows Vulkan loader.

**Comment by 06393993** [comment] 2023-03-28 23:53
We have verified on the problematic machine that vulkaninfo with the 1.3.231.1, 1.3.239.0 vulkan-1.dll shipped on [the LunarG website](https://vulkan.lunarg.com/sdk/home#windows) will fail with INCOMPLETE while the 1.3.224.1 vulkan-1.dll  can work, so it's probably a regression in the Windows Vulkan loader.

However, users with those released Vulkan loaders can still suffer from such issue. IMO, panic or bump-retry-and-panic is still better than an infinite loop. WDYT?

**Comment by Ralith** [comment] 2023-03-30 02:20
Has an issue been reported upstream?

**Comment by 06393993** [comment] 2023-03-30 02:35
> Has an issue been reported upstream?

https://github.com/KhronosGroup/Vulkan-Loader/issues/1165

**Comment by Ralith** [comment] 2023-03-30 02:59
Per that thread, it sounds like the issue is in a **2019** build of a layer included with AMD drivers, not a recent version of the loader as suggested above. I'm not sure it's a good idea to bake in hacks around such an old and niche issue. End users experiencing unexpected behavior should always be instructed to ensure their video drivers are up to date.

**Comment by 06393993** [comment] 2023-03-30 16:58
Is it possible to accept a several-line patch over `read_into_uninitialized_vector` to panic when the underlying driver is buggy and returns an unexpected `VK_INCOMPLETE`? We don't have to introduce a complicated algorithm to entirely workaround the issue, panic is enough since it's much easier to debug compared to an infinite loop.

Demonstrating the issues, I just want to be convincing that such an issue can happen on end users' machines, which we don't have control over of. Since it is not guaranteed that such issues won't happen in the future, so it is possible that latest driver may have a similar issue in the future. Therefore, we want to be using the Vulkan API in a defensive way, so that our program at least won't hang which makes it very difficult to diagnose what happens.

In addition, users can install many implicit Vulkan layers(e.g. OBS, Overwolf) which can be buggy, although not necessarily the same issue, so I think it's always helpful to be defensive. For software that we want to have some kind of defined behavior on a slightly buggy driver, is the suggestion to move away from `ash` or workaround outside `ash`?

Having said so, I also understand if `ash` doesn't want to accept the patch, because the official Vulkan-Hpp also will [trap in a similar infinite loop](https://github.com/KhronosGroup/Vulkan-Headers/blob/0c34d02861745528b85c082e4f84f2c82bde8772/include/vulkan/vulkan_funcs.hpp#L135-L143) under such circumstances.

**Comment by idanraiter** [comment] 2023-03-30 18:10
Opened https://github.com/ash-rs/ash/pull/730 to make the proposal concrete.

**Comment by idanraiter** [comment] 2023-04-10 18:07
Hey again! Wanted to check in to see if there is an interest in this PR (or we can close it). An alternative is to manually call the raw enumerate_physical_devices, check for INCOMPLETE, and if so avoid using Vulkan (so pushing the check to users of ash). Let us know which way makes more sense to you.

**Comment by Ralith** [comment] 2023-04-10 18:38
> Since it is not guaranteed that such issues won't happen in the future, so it is possible that latest driver may have a similar issue in the future

This is not a compelling argument. It is always possible that a buggy layer could do literally anything, and this having happened once four years ago only makes it slightly more likely to recur than any other arbitrary behavior. It is impossible for ash, or any software, to be robust against arbitrary misbehavior. If we added mitigations to every upstream bug we could imagine, or even merely every bug that has been observed in the wild, ash would rapidly become unmaintainable, even if the mitigations were individually small.

**Comment by idanraiter** [comment] 2023-04-12 16:58
Thanks for the clarification & review! I'm going to go ahead and close this issue / PR, and we will use the workaround instead.

**Closed** 2023-04-12 18:48 UTC

**Comment by MarijnS95** [comment] 2023-04-12 18:57
Thanks! I wasn't quite sure what to do with the PR while discussions were still well underway.
